### ISSUE TITLE
Infobar entity issue

### ISSUE THREAD

**Issue by KenshiDRK** [Windower/Issues#728]
Infobar is detecting all entities as npc.

**Comment by z16** [comment]
This should be fixed as of a few days ago.

**Comment by DrynnCabal** [comment]
The issue first appeared immediately after the patch a few days ago. It is still not functioning properly.

**Comment by KenshiDRK** [comment]
Its working properly for me, make sure you have the last version.

**Comment by DrynnCabal** [comment]
Gah, I fail.  The version was the problem.
