### ISSUE TITLE
ffxidb dont show npc or any targets

### ISSUE THREAD

**Issue by joso33** [Windower/Issues#730]
ffxidb plugin only show the map, no npc or targets what so ever.

**Comment by z16** [comment]
This should be fixed as of a few days ago.

**Comment by DrynnCabal** [comment]
The issue first appeared immediately after the patch a few days ago.  It is still not functioning properly.

**Comment by DrynnCabal** [comment]
Disregard, I had a version conflict.
