### ISSUE TITLE
Return of Creator's Update Issues with Windows 10 Build 16251

### ISSUE THREAD

**Issue by VelesX-III** [Windower/Issues#942]
I've already briefly discussed this on FFXIAH, but as this is the official place to bug Byrth and the team, I'll do it here too. Anyway, I'm on the Insider Preview build in the title, and the issues launching POL after selection of a Windower profile seem to be an immanent issue once this update gets released to the general public. The issues I will describe are hardly new, but the fixes rendered before are no longer serving anymore.

**Description of the problem(s):**
1.) Windower will either crash while attempting to launch POL.
2.) If _(1)_ does not happen, then Windower will exit after the "Launching PlayOnline" screen apparently normally, but fails to actually launch POL.
*It should be noted that PlayOnline and FFXI function perfectly fine without Windower.

Here is the log entry from _(1)_ above:
`Faulting application name: Windower.exe, version: 4.3.6349.31918, time stamp: 0x5920b89d
Faulting module name: KERNELBASE.dll, version: 10.0.16251.0, time stamp: 0x92105574
Exception code: 0xe0434352
Fault offset: 0x000ffa82
Faulting process id: 0x1b8c
Faulting application start time: 0x01d30b6de394f924
Faulting application path: C:\Program Files (x86)\Windower4\Windower.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b9af17dd-3b6d-4bb6-af51-5a0c08ee3c1f
Faulting package full name: 
Faulting package-relative application ID: `

And here is the log for _(2)_ as described above:
`Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
Faulting module name: KERNELBASE.dll, version: 10.0.16251.0, time stamp: 0x92105574
Exception code: 0xc06d007e
Fault offset: 0x000ffa82
Faulting process id: 0x618
Faulting application start time: 0x01d30c4b1d98e591
Faulting application path: C:\Program Files (x86)\PlayOnline\SquareEnix\PlayOnlineViewer\pol.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8dec85ee-118b-40ee-b56f-127ae7de1dad
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by cairface** [comment]
Hello~

Sorry for the delay, but I just updated my laptop to the latest insider preview (now 16257.1) and I can't replicate this issue with Windower 4. If you update your insider version, does the problem persist?

**Comment by VelesX-III** [comment]
I'm now installing the latest update on the experimental Windows branch. In the mean time, I got the four log entries for _(1)_ as I described in my original post. Here they are in reverse chronological order, and the first two occur while Windower is still attempting to launch POL. The top two occur after I get the "Windower has stopped working" message.

> Faulting application name: Windower.exe, version: 4.3.6349.32679, time stamp: 0x5920be8f
> Faulting module name: KERNELBASE.dll, version: 10.0.16251.0, time stamp: 0x92105574
> Exception code: 0xe0434352
> Fault offset: 0x000ffa82
> Faulting process id: 0x15e0
> Faulting application start time: 0x01d317c84c99ce17
> Faulting application path: C:\Program Files (x86)\Windower4\Windower.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 56748812-5e6c-44bd-a8be-1e167aa94038
> Faulting package full name: 
> Faulting package-relative application ID: 

> Application: Windower.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ComponentModel.Win32Exception
>    at Launcher.Injector.Inject(Launcher.SafeSystemHandle, System.String, Settings, System.TimeSpan)
>    at Launcher.Injector.Launch(System.String, Launcher.Profile, Boolean, System.TimeSpan)
>    at Launcher.Tasks.LaunchTask.Run()
>    at Launcher.Tasks.Task.Run(Launcher.Core)
>    at Launcher.Core.Run()
>    at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.ThreadHelper.ThreadStart()

> Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
> Faulting module name: KERNELBASE.dll, version: 10.0.16251.0, time stamp: 0x92105574
> Exception code: 0xe06d7363
> Fault offset: 0x000ffa82
> Faulting process id: 0x778
> Faulting application start time: 0x01d317c850344567
> Faulting application path: C:\Program Files (x86)\PlayOnline\SquareEnix\PlayOnlineViewer\pol.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 6d2b4105-c780-4bf3-97e8-29158490287e
> Faulting package full name: 
> Faulting package-relative application ID: 

> Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
> Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
> Exception code: 0xc0000005
> Fault offset: 0x00000000
> Faulting process id: 0x778
> Faulting application start time: 0x01d317c850344567
> Faulting application path: C:\Program Files (x86)\PlayOnline\SquareEnix\PlayOnlineViewer\pol.exe
> Faulting module path: unknown
> Report Id: 5834425d-e805-4e9c-93d6-a3ccbceb2bd1
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by cairface** [comment]
Deleted my first reply because Windows didn't successfully update to the insider build despite not outwardly indicating that anything went wrong and I'm trying to troubleshoot the issue. Once it's updated, I'll know more. That said, these error logs are not useful to us. A crash dump would be greatly appreciated and provide insight into the crash.

**Comment by VelesX-III** [comment]
[dumps.zip](https://github.com/Windower/Issues/files/1237062/dumps.zip)

As requested, here are the dumps. Thank you for looking into to all this.

**Comment by cairface** [comment]
Hello~

I addressed a potential issue on the insider preview version. If you have the time and want to try out this hook and let me know if you still encounter issues, that would be great:

https://www.dropbox.com/s/ddbhqr2n8ww98t7/Hook.dll?dl=0

**Comment by VelesX-III** [comment]
I tested it, but the issue persists. Here are dumps from the above hook.

Addendum: The hook was placed in the spot of the normal hook that the launcher downloads. It should be noted that Windower Launcher still records the version of the hook as 4.3.2.1.

[dumps.zip](https://github.com/Windower/Issues/files/1237405/dumps.zip)

**Comment by VelesX-III** [comment]
My apologies! I did not mean to close the issue. This was a mistake.

**Comment by VelesX-III** [comment]
Okay, Microsoft has released the experimental builds to the general release channel as the "Fall Creators Update" with build number 16288. The nature of the issue is now a little less mysterious and actually bears some error codes in the case of the outright crash as I described above:

![windower screenshot](https://user-images.githubusercontent.com/12122119/30510368-30cc67a0-9a77-11e7-94ba-2797a8739f1f.PNG)

Soon, many more people will come to experience this issue, I fear now that the update is public.

**Comment by z16** [comment]
As a quick update, we have finally identified the issue, working on fixing it now.

**Comment by Selindrile** [comment]
\^^/

**Comment by IBHalliwell** [comment]
Just FYI:  I found the problem on the Official Fall Creator Update (not a preview).  It is being pushed out to people.

**Comment by cairface** [comment]
It's almost definitely the same issue. We're currently looking into it, thanks for the report!

**Comment by cairface** [comment]
We pushed an updated hook to both the live and dev versions of windower that has addressed the problem. Please let us know if there are still any issues.

**Comment by VelesX-III** [comment]
The issue is not fixed. The same symptoms still persist. What version and build of Windows 10 did you try it on? I am on version 1709 build 16299.19.

**Comment by z16** [comment]
Did you actually update Windower? I have to ask since a) it's seems resolved for everyone else and b) people tend to find ways to block updates when such issues arise.

If you did and it persists it's likely due to something else, due to a). I'm also on the exact same version and build as you and it works for me. In which case we'll need to debug some more, so if you could provide us with crash dumps and the `crash.log` file, if a file like that exists, we would appreciate it.

**Comment by VelesX-III** [comment]
The version updated successfully. Here's a dump:
[dumps.zip](https://github.com/Windower/Issues/files/1413611/dumps.zip)

**Comment by cairface** [comment]
Can you give this a try? https://www.dropbox.com/s/uqajrws6gce91zk/Windower.exe?dl=0

**Comment by VelesX-III** [comment]
I found that the problem is caused by using Windower with atom0s's D3D pipeline DLL's. When I delete those DLL's, it all works fine. Should I make a separate thread regarding that issue? I imagine it could be of great benefit to the Windower project to grant superior compatibility for Windows 10 machines.

I do apologize for being that daft to not realize this though.

**Comment by joshk6656** [comment]
His hooks are specifically created not to work with windower. Nothing we
can do to fix.

**Comment by z16** [comment]
Quoth the atom0s: "As for this not working with Windower, it is not something that is broken. It is intentionally coded that way."

**Comment by VelesX-III** [comment]
Well then, that settles that. Byrth said Windower 5 will have a totally re-written hooking API, so I imagine that day will come with integrated pipelining.

**Comment by z16** [comment]
Not planned as of today, I'm afraid. But we'll see what the future holds.

**Comment by cairface** [comment]
@VelesX-III You can try using this for now. At0mos specifically blocks windower in that DLL, unfortunately.

https://www.dropbox.com/s/67pclbff2q4ho7p/d3d%20proxy%20windower%20fix.7z?dl=0

**Comment by VelesX-III** [comment]
This produces the same issue as atom0s' pipeline. It's for Windower usage though? Does it require an .ini file to properly work? Do I place it in the POL Viewer folder, or elsewhere?

**Comment by cairface** [comment]
It's the same dll, just patched so that it doesn't crash if it detects
windower. It requires the same setup

**Comment by Bvlcony** [comment]
Can you please link what changes exactly were made to fix that crash problem?

**Comment by joshk6656** [comment]
Are you talking about the DirectX proxy or windower?
